CREATE TABLE `monthly_social_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`monthKey` varchar(7) NOT NULL,
	`accountsReached` int,
	`views` int,
	`interactions` int,
	`netFollowers` int,
	`reelsPublished` int,
	`reelsMedianReach` int,
	`reelsMedianViews` int,
	`reelsMedianInteractions` int,
	`reelsMedianSharesSaves` int,
	`carouselsPublished` int,
	`carouselsMedianReach` int,
	`carouselsMedianViews` int,
	`carouselsMedianInteractions` int,
	`carouselsMedianSharesSaves` int,
	`storiesPublished` int,
	`storiesMedianReach` int,
	`storiesMedianViews` int,
	`storyReplies` int,
	`storyLinkClicks` int,
	`storyStickerTaps` int,
	`storyProfileVisits` int,
	`note` text NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `monthly_social_results_id` PRIMARY KEY(`id`),
	CONSTRAINT `monthly_social_results_monthKey_unique` UNIQUE(`monthKey`)
);
