CREATE TABLE `lead_profile_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sourceKey` varchar(64) NOT NULL,
	`periodStartAt` bigint NOT NULL,
	`periodEndAt` bigint NOT NULL,
	`totalLeads` int NOT NULL,
	`newLeads` int NOT NULL,
	`firstTimeCount` int,
	`attended2026Count` int,
	`attendedPastCount` int,
	`nutritionAestheticsCount` int,
	`sportsNutritionCount` int,
	`sportsPhysioCount` int,
	`businessManagementCount` int,
	`physicalEducationCount` int,
	`bodybuildingCount` int,
	`otherInterestCount` int,
	`singleInterestCount` int,
	`multipleInterestsCount` int,
	`topCitiesJson` text NOT NULL,
	`note` text NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `lead_profile_snapshots_id` PRIMARY KEY(`id`)
);
