CREATE TABLE `masterclass_landing_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`periodStartAt` bigint NOT NULL,
	`periodEndAt` bigint NOT NULL,
	`totalLeads` int NOT NULL,
	`newLeads` int NOT NULL,
	`sessions` int,
	`dmSessions` int,
	`formStarts` int,
	`dmConversions` int,
	`thankYouPageAccesses` int,
	`anaLessonStarts` int,
	`anaLessonCompletions` int,
	`andreiaLessonStarts` int,
	`andreiaLessonCompletions` int,
	`robertoLessonStarts` int,
	`robertoLessonCompletions` int,
	`congressHubClicks` int,
	`newsLpClicks` int,
	`salesPageClicks` int,
	`note` text NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `masterclass_landing_snapshots_id` PRIMARY KEY(`id`)
);
